apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: all-helm-charts
spec:
  generators:
  - matrix:
      generators:
        - merge:
          mergeKeys:
            - path
          generators:
            - git:
                repoURL: https://github.com/bitnami/charts.git
                revision: HEAD
                directories:
                - path: bitnami/*
            - git:
                repoURL: https://github.com/bitnami/charts.git
                revision: HEAD
                files:
                - path: bitnami/**/values.yaml
        - clusters:
            selector:
              matchLabels:
                vcluster: "true"
  template:
    metadata:
      name: '{{cluster}}-{{releaseName}}'
    spec:
      project: default
      source:
        chart:  '{{path.basename}}'
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        helm:
          releaseName: '{{releaseName}}'
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true