apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nested-generators-appset
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  vcluster: "true"
          - list:
              elements:
                - env: dev
                  replicas: "1"
                - env: staging
                  replicas: "2"
                - env: prod
                  replicas: "3"
    - git:
        repoURL: https://github.com/argo-multiverse-labs/basic-app
        revision: main
        directories:
          - path: app-chart
    - merge:
        mergeKeys:
          # Note that this would not work with goTemplate enabled,
          # nested merge keys are not supported there.
          - values.selector
        generators:
          # Assuming, all configured clusters have a label for their location:
          # Set the selector to this location.
          - clusters:
              values:
                selector: '{{index .name}}'
          # The git repo may have different directories which correspond to the
          # cluster locations, using these as a selector.
          - git:
              repoURL: https://github.com/argoproj/argocd-example-apps/
              revision: HEAD
              directories:
              - path: '*'
              values:
                selector: '{{.path.path}}'
    - pullRequest:
        github:
          owner: argo-multiverse-labs
          repo: basic-app
          labels:
            - preview
        requeueAfterSeconds: 300
  template:
    metadata:
      name: '{{name}}-{{env}}-{{cluster.name}}-{{version}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/argo-multiverse-labs/basic-app
        targetRevision: '{{version}}'
        path: '{{path}}'
      destination:
        server: '{{cluster.server}}'
        namespace: apps
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      replicas: '{{replicas}}'